# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a77e863b9b83efbe1e3c49603233b80b825f15df86ee20503ce3a340ad2160733451b5f1f25ffa9da9149787decc97b5aa7775ed0d8fb73e240b2bf725baeb6

test:
  secret_key_base: 422dd3039ec33f84e23c80759fadfb6e9c1a2c52bd1ebdfc86492388968bcad96a3705c800dd6cbe5df1c8bac67865e72eee859d26eb9ff42e93cf0e38758983

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
